name: build

# only run on changes to main
on:
  push:
    branches:
      - main

concurrency: # prevent concurrent deploys doing strange things
  group: build-and-push
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: gh-pages
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: lts/*
    - name: Install deps and build
      run: |
        npm i
        grunt
    - name: Push to gh-pages
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: gh-pages
        push_options: '--force'
        commit_message: Generate templated files